### ISSUE TITLE
How MICA headers correspond to output files?

### ISSUE THREAD

**Issue by twang15** [boegel/MICA#11]
In tableGen.sh, headers are arranged in a pre-defined order.
And in line 28, "cat *$i_pid* | tr -d "\n" >> ../micaTable.txt" put all collected data in one file.

The question is that how can we know that the mapping from a head to a mica metric is correct?

**Comment by twang15** [comment]
In fact, with the following mica.conf, there are 93 metrics collected, while tableGen.sh generates 99 metrics. 

analysis_type: all
interval_size: full
ilp_size: 32
page_size: 12
block_size: 6
itypes_spec_file: itypes_default.spec
append_pid: yes

**Comment by twang15** [comment]
Within each files, the output looks like:

[twang15@c93 ls]$ cat ilp_full_int_4168_pin.out
1479335 264049 225244 204819 193130
number of instructions: 1460931

There are two issues:
1. No header for each metric. So one cannot know what the number really means.
2. There are always the 2nd line in each *.out file. Such format is inconsistent with v0.4, since tableGen.sh assumes there is exactly 1 line per *.out file.

**Comment by twang15** [comment]
@amirjamez

**Comment by twang15** [comment]
I also notice that the collected metrics are also redundant.
For example, 1526336 has appeared several times.

APPLICATION_NAME DATASET totInstruction ILP32 ILP64 ILP128 ILP256 total_ins_count_for_hpc_alignment totInstruction mem-read mem-write control-flow arithmetic floating-point stack shift string sse other nop  InstrFootprint64 InstrFootprint4k DataFootprint64 DataFootprint4k mem_access memReuseDist0-2 memReuseDist2-4 memReuseDist4-8 memReuseDist8-16 memReuseDist16-32 memReuseDist32-64 memReuseDist64-128 memReuseDist128-256 memReuseDist256-512 memReuseDist512-1k memReuseDist1k-2k memReuseDist2k-4k memReuseDist4k-8k memReuseDist8k-16k memReuseDist16k-32k memReuseDist32k-64k memReuseDist64k-128k memReuseDist128k-256k memReuseDist256k-512k memReuseDist512k-00 GAg_mispred_cnt_4bits PAg_mispred_cnt_4bits GAs_mispred_cnt_4bits PAs_mispred_cnt_4bits GAg_mispred_cnt_8bits PAg_mispred_cnt_8bits GAs_mispred_cnt_8bits PAs_mispred_cnt_8bits GAg_mispred_cnt_12bits PAg_mispred_cnt_12bits GAs_mispred_cnt_12bits PAs_mispred_cnt_12bits total_brCount total_transactionCount total_takenCount total_num_ops instr_reg_cnt total_reg_use_cnt total_reg_age reg_age_cnt_1 reg_age_cnt_2 reg_age_cnt_4 reg_age_cnt_8 reg_age_cnt_16 reg_age_cnt_32 reg_age_cnt_64 mem_read_cnt mem_read_local_stride_0 mem_read_local_stride_8 mem_read_local_stride_64 mem_read_local_stride_512 mem_read_local_stride_4096 mem_read_local_stride_32768 mem_read_local_stride_262144 mem_read_global_stride_0 mem_read_global_stride_8 mem_read_global_stride_64 mem_read_global_stride_512 mem_read_global_stride_4096 mem_read_global_stride_32768 mem_read_global_stride_262144 mem_write_cnt mem_write_local_stride_0 mem_write_local_stride_8 mem_write_local_stride_64 mem_write_local_stride_512 mem_write_local_stride_4096 mem_write_local_stride_32768 mem_write_local_stride_262144 mem_write_global_stride_0 mem_write_global_stride_8 mem_write_global_stride_64 mem_write_global_stride_512 mem_write_global_stride_4096 mem_write_global_stride_32768 mem_write_global_stride_262144
ls dataset1 1526336 271860 232593 212124 1999181526336 378877 208977 332149 966897 0 91087 21474 19050 17352 66054 7034 52354864 195 2579 192379953 4383 193276 32868 31297 39506 25211 14886 19740 13668 2413 873 1216 606 10 0 0 0 0 0 01526336 39230 15644 18031 24622 63558 17423 17164 20790 76027 20684 17821 18347 260531 23101 205991526336 2643258 921667 1592189 1689487 392046 520440 705120 923860 1108786 1264209 1379069379409 16736 250175 297414 330115 344855 349733 350779 3401 95450 152725 179779 191815 223511 225353 208977 4854 155914 173904 198908 201363 202956 203215 233 50924 157862 187924 191480 192102 192152

**Comment by amirjamez** [comment]
@twang15 it should be 99 columns. You might have missed one category, or, it might not have been aggregated by the tableGen. Have a look at [COBAYN's data here](https://github.com/amirjamez/COBAYN#provided-datasets) 
For each individual category see the code and the [README](https://github.com/boegel/MICA#full-execution-metrics). The tableGen makes sure to find and aggregates the features by alphabetic order, thus we always have the same ordering of 99 columns when we use it. As COBAYN did and is a common practice, you should purge the unwanted columns, remove redundant, normalize and then apply a dimension reduction technique such as PCA. Refer to COBAYN's preprocessing code and also the paper.

**Comment by twang15** [comment]
@amirjamez COBAYN's mica data only has 47 columns.

I am not sure what is misconfigured. But w/ the following configuration, there are only 97 columns while the table header has 101 columns.  

analysis_type: all
interval_size: full
page_size: 12
block_size: 6
itypes_spec_file: itypes_default.spec
append_pid: yes

There are 7 files generated.

ilp_full_int_10257_pin.out     
memfootprint_full_int_10257_pin.out  
ppm_full_int_10257_pin.out  
stride_full_int_10257_pin.out
itypes_full_int_10257_pin.out  
memstackdist_full_int_10257_pin.out  
reg_full_int_10257_pin.out

**Comment by twang15** [comment]
@amirjamez One possibility is due to misconfiguration, but there is no documentation to mention how to properly configure mica for all 101 columns.

**Comment by amirjamez** [comment]
@twang15 the tableGen assumes the 1st and 2nd column for application and dataset name. Ignore them and you have 99. So, those 47 columns might be the preprocessed columns I made by removing duplicates and redundant. use those only and apply PCA to make them 10.

**Comment by twang15** [comment]
@amirjamez 

tableGen.sh has 101 columns for table header, including the 1st column for application name and the 2nd for dataset name.
So, excluding the 1st and 2nd column, there should be 99 mica metrics.

But, with above mica configuration, only 97 columns (including 1st column for application name and 2nd for dataset name) are available. In other words, mica only generates 95 metrics, while 99 metrics is expected by tableGen.sh.

I believe there is sth wrong with tableGen.sh or mica is misconfigured as above.

**Comment by twang15** [comment]
I have figured out the root cause.
There is indeed a bug.
I will report and resolve it in a new issue.

**Comment by twang15** [comment]
See fix #12
