### ISSUE TITLE
What is the meaning of 2 values in register traffic

### ISSUE THREAD

**Issue by WilliamWangPeng** [boegel/MICA#21]
Hi dear author,  
    I have read the MICA article which says 2 values and 7 probabilities in register traffic as follwing shows:  

![image](https://user-images.githubusercontent.com/51076736/117482120-85d1b380-af96-11eb-8e1c-e5c5d887fe3a.png)  

and I have tested a set of data abot register traffic here:  

![image](https://user-images.githubusercontent.com/51076736/117482160-91bd7580-af96-11eb-9018-8d62c209fd69.png)  

I wonder which number is average number of register input operands per instruction, which is number of register reads per register write.  

thank you  
Best Regards to you  
William

**Comment by boegel** [comment]
It's been way too long since I've looked at this myself (over 10 years...), but I think it should be easy to deduce from the source code what those numbers mean exactly, see https://github.com/boegel/MICA/blob/master/mica_reg.cpp#L319 (I think)

**Comment by amirjamez** [comment]
Hi @WilliamWangPeng,

As @boegel mentioned, you can refer to the code to understand the output values. Feel free to have a look at the README.md file we provided in the repo. Also, If you use `analysis_type: all`, it will emit almost ~100 metrics and we have provided a tablegen utility to generate a table of CSV for those. Have a look at line 10 to see the names: 

https://github.com/boegel/MICA/blob/master/tableGen.sh#L10

- Amir

**Comment by WilliamWangPeng** [comment]
> Hi @WilliamWangPeng,
> 
> As @boegel mentioned, you can refer to the code to understand the output values. Feel free to have a look at the README.md file we provided in the repo. Also, If you use `analysis_type: all`, it will emit almost ~100 metrics and we have provided a tablegen utility to generate a table of CSV for those. Have a look at line 10 to see the names:
> 
> https://github.com/boegel/MICA/blob/master/tableGen.sh#L10
> 
> * Amir

thank you so much dear @amirjamez   
    Another question is where to put the PID number in the tableGen.sh, so that I can use tableGen.sh to generate the a CSV file

![image](https://user-images.githubusercontent.com/51076736/117523084-762f8a80-afe9-11eb-8984-b283e2725f52.png)

![image](https://user-images.githubusercontent.com/51076736/117523091-7def2f00-afe9-11eb-9271-3d95c0e81936.png)  

for example, my PID number here is 19060

thank you  
best regards  
William

**Comment by WilliamWangPeng** [comment]
> Line 24 of the script finds the unique PID of all analysis types so it concats the features of the same analysis into one csv.

yes, I have noticed the line 24, I tried to replace the sed to 19060, but failed, and later I could just see the headers in micaTable.txt which has no data.  

![image](https://user-images.githubusercontent.com/51076736/117525334-4fc31c80-aff4-11eb-8523-bdb4df90a10f.png)

**Comment by WilliamWangPeng** [comment]
open another issue

**Comment by amirjamez** [comment]
@WilliamWangPeng `pidList` returns a list of PIDs MICA generated. Every time you run MICA, the output files are named with a new PID. It looks for all output files having the `same` PID, and later it iterates over them to generate the CSV file.
